plugins {
    id 'com.android.application'
}

def screenshotBuild = project.hasProperty('screenshotBuild')

android {
    namespace 'com.xziel.iw4native'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xziel.iw4native'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.3-sanctum-nzp-floating'

        ndk {
            if (screenshotBuild) {
                abiFilters 'x86_64'
            } else {
                abiFilters 'arm64-v8a'
            }
        }

        externalNativeBuild {
            cmake {
                arguments '-DIW4NATIVE_BUILD_TESTS=OFF'
                cppFlags '-std=c++20'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('../../CMakeLists.txt')
            version '3.22.1'
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging false
        }
    }
}
