plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xziel.iw4native'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xziel.iw4native'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '0.2-sanctum-nzp-radial'

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                arguments '-DIW4NATIVE_BUILD_TESTS=OFF'
                cppFlags '-std=c++20'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('../../CMakeLists.txt')
            version '3.22.1'
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging false
        }
    }
}
