#!/usr/bin/env python3
"""Generate the provisional Footlight District G3 blockout as a Valve 220 .map."""

from __future__ import annotations
import argparse, json
from pathlib import Path
from generate_soe_g1_blockout import (
    box_brush, point_entity, brush_entity, stair_boxes, stair_boxes_y,
    FLOOR_TEX, WALL_TEX, CEILING_TEX, BLOCK_TEX, TRIGGER_TEX, NULL_TEX,
)

from soe_mainquest_geometry import append_phase_mainquest_entities

ROOT=Path(__file__).resolve().parents[1]
SPEC_PATH=ROOT/"content"/"shadows_of_evil"/"g3_footlight_blockout.json"
OUTPUT_PATH=ROOT/"overlay"/"assets"/"source"/"maps"/"soe_g3"/"soe_g3.map"
WORLD_WAD="../../textures/wad/Example_02.wad"

def gen(spec):
    ents,wb=[],[]

    wb += [
        box_brush((576,-768,-128),(1920,768,-96),FLOOR_TEX),
        box_brush((576,-768,-96),(608,768,512),WALL_TEX),
        box_brush((1888,-768,-96),(1920,768,512),WALL_TEX),
        box_brush((576,-768,-96),(1920,-736,512),WALL_TEX),
        box_brush((576,736,-96),(1920,768,512),WALL_TEX),
        box_brush((576,-768,512),(1920,768,544),CEILING_TEX),
    ]

    # Entry / lower street.
    wb += [
        box_brush((640,-256,-16),(912,256,0),FLOOR_TEX),
        box_brush((896,-448,-16),(1408,448,0),FLOOR_TEX),
        # Facade masses create a long lower street corridor.
        box_brush((896,272,0),(1328,448,224),WALL_TEX),
        box_brush((896,-448,0),(1328,-272,224),WALL_TEX),
        box_brush((1328,272,0),(1408,448,224),WALL_TEX),
        box_brush((1328,-448,0),(1408,-272,224),WALL_TEX),
    ]

    # Traffic-jam obstacles: low enough to vault/route around, not full blockers.
    for mi,ma in [
        ((960,-176,0),(1080,-80,44)),
        ((1088,64,0),(1216,152,44)),
        ((1232,-208,0),(1360,-112,44)),
        ((1120,-32,0),(1224,32,40)),
    ]:
        wb.append(box_brush(mi,ma,BLOCK_TEX))

    # High Street narrow walkways + stairs.
    wb += [
        box_brush((928,256,112),(1568,320,128),BLOCK_TEX),
        box_brush((928,512,112),(1568,576,128),BLOCK_TEX),
        box_brush((928,320,112),(992,576,128),BLOCK_TEX),
        box_brush((1504,320,112),(1568,576,128),BLOCK_TEX),
    ]
    for a,b in stair_boxes_y(944,160,0,8,20,16,96,1):
        wb.append(box_brush(a,b,BLOCK_TEX))

    # Black Lace shell + stage.
    wb += [
        box_brush((1296,-272,-16),(1776,-256,416),WALL_TEX),
        box_brush((1296,256,-16),(1776,272,416),WALL_TEX),
        box_brush((1760,-256,-16),(1776,256,416),WALL_TEX),
        box_brush((1296,-256,-16),(1312,-80,416),WALL_TEX),
        box_brush((1296,80,-16),(1312,256,416),WALL_TEX),
        box_brush((1312,-256,-16),(1760,256,0),FLOOR_TEX),
        box_brush((1456,-64,0),(1648,160,24),BLOCK_TEX),
        # Roof/sign platform for Beast landing.
        box_brush((1456,-160,288),(1648,64,304),BLOCK_TEX),
    ]

    # Footlight station.
    wb += [
        box_brush((1392,304,-16),(1856,336,0),FLOOR_TEX),
        box_brush((1392,336,-16),(1856,704,0),FLOOR_TEX),
        box_brush((1392,704,-16),(1856,720,0),FLOOR_TEX),
        box_brush((1392,336,0),(1424,704,224),WALL_TEX),
        box_brush((1824,336,0),(1856,704,224),WALL_TEX),
        box_brush((1392,336,224),(1856,704,240),CEILING_TEX),
        box_brush((1504,432,0),(1760,472,8),BLOCK_TEX),
        box_brush((1504,560,0),(1760,600,8),BLOCK_TEX),
    ]

    # Rift pocket.
    wb += [
        box_brush((816,-624,-80),(1072,-608,128),WALL_TEX),
        box_brush((816,-400,-80),(1072,-384,128),WALL_TEX),
        box_brush((816,-608,-80),(832,-400,128),WALL_TEX),
        box_brush((1056,-608,-80),(1072,-400,128),WALL_TEX),
        box_brush((816,-608,-80),(1072,-400,-64),FLOOR_TEX),
    ]

    world=[
        "// Game: Nazi Zombies Portable","// Format: Valve",
        "// AUTO-GENERATED by scripts/generate_soe_g3_footlight.py",
        "{",'"mapversion" "220"',f'"wad" "{WORLD_WAD}"','"classname" "worldspawn"',
        '"chaptertitle" "Shadows of Evil - G3 Footlight Blockout"',
        '"location" "Morg City - Footlight District"',
        '"person" "NZ:P Android clean-room reconstruction"','"light" "72"'
    ]
    for i,b in enumerate(wb): world += [f"// brush {i}",b]
    world.append("}")
    ents.append("\n".join(world))

    for i,(x,y) in enumerate([(720,-72),(720,-24),(720,24),(720,72)],1):
        ents.append(point_entity(f"info_player_{i}_spawn",(x,y,40),weapon=0,currentmag=0,currentammo=0,angle=0))

    zones=[
        ("footlight_entry",(640,-256,0),(896,256,192),"soe_g3_entry","footlight_main"),
        ("footlight_main",(896,-448,0),(1408,448,224),"soe_g3_main","footlight_entry, footlight_high, black_lace, footlight_rift"),
        ("footlight_high",(928,192,128),(1568,640,352),"soe_g3_high","footlight_main, footlight_station"),
        ("black_lace",(1312,-256,0),(1760,256,416),"soe_g3_black_lace","footlight_main"),
        ("footlight_station",(1408,320,0),(1840,720,320),"soe_g3_station","footlight_high"),
        ("footlight_rift",(832,-608,-64),(1056,-400,128),"soe_g3_rift","footlight_main"),
    ]
    for name,mi,ma,target,adj in zones:
        ents.append(brush_entity("spawn_zone",mi,ma,TRIGGER_TEX,zone_name=name,zone_target=target,adjacent_zones=adj))

    spawn_defs=[
        ((832,192,40),"soe_g3_entry",180),((832,-192,40),"soe_g3_entry",180),
        ((944,400,40),"soe_g3_main",270),((1328,-400,40),"soe_g3_main",90),
        ((960,544,160),"soe_g3_high",270),((1512,544,160),"soe_g3_high",270),
        ((1360,-208,40),"soe_g3_black_lace",0),((1712,208,40),"soe_g3_black_lace",180),
        ((1456,672,40),"soe_g3_station",270),((1792,672,40),"soe_g3_station",270),
    ]
    for org,target,ang in spawn_defs:
        ents.append(point_entity("spawn_zombie",org,spawnflags=7,angle=ang,targetname=target))

    for a in spec["gameplayAnchors"]:
        keys={k:v for k,v in a.items() if k not in {"classname","origin"}}
        ents.append(point_entity(a["classname"],a["origin"],**keys))

    for d in spec["poweredGeometry"]:
        ents.append(brush_entity(d["classname"],d["mins"],d["maxs"],NULL_TEX,targetname=d["targetname"]))

    for group in spec["randomized"]:
        for n,org in enumerate(group["candidates"],1):
            keys={"soe_random_group":group["group"],"targetname":f"soe_g3_random_{group['group']}_{n}","style":group["style"]}
            ents.append(point_entity(group["entity"],org,**keys))

    # Rift is intentionally inert in G3.
    ents.append(point_entity("info_notnull",(944,-512,-24),targetname="soe_g3_rift_portal_anchor"))

    # Civil/quest-support workbench.
    ents.append(point_entity("soe_shield_build_table",(1040,336,40),targetname="soe_g3_shield_table"))
    ents.append(point_entity("soe_servant_build_table",(1096,336,40),targetname="soe_g3_servant_table"))

    # Two Mystery Box candidate points, retained as native NZ:P box locations.
    ents.append(point_entity("mystery_box_tp_spot",(1016,-344,32),angles="0 90 0",model="models/machines/mystery.mdl"))
    ents.append(point_entity("mystery_box_tp_spot",(1592,376,32),angles="0 180 0",model="models/machines/mystery.mdl"))

    # Placeholder anchors for machine/side-detail positions not yet backed by a native GobbleGum runtime.
    ents.append(point_entity("info_notnull",(1040,-240,40),targetname="soe_g3_gobblegum_anchor_a"))
    ents.append(point_entity("info_notnull",(1712,416,40),targetname="soe_g3_gobblegum_anchor_b"))

    # Cross-phase Reborn Sword / Flag quest anchors from the shared source of truth.
    append_phase_mainquest_entities(ents, "g3", point_entity)

    for org,b in [((800,0,176),300),((1120,0,192),260),((1248,384,256),220),
                  ((1544,0,192),300),((1632,520,176),300),((944,-512,64),180)]:
        ents.append(point_entity("light",org,_light=b,wait=1,style=0))

    return "\n".join(ents)+"\n"

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--check",action="store_true"); args=ap.parse_args()
    spec=json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    out=gen(spec)
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != out:
            raise SystemExit("G3 map is stale; regenerate it")
        print("SOE G3 generated map is deterministic and up to date"); return
    OUTPUT_PATH.parent.mkdir(parents=True,exist_ok=True)
    OUTPUT_PATH.write_text(out,encoding="utf-8",newline="\n")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")

if __name__=="__main__": main()
