#!/usr/bin/env python3
"""Generate the provisional Canal District G2 blockout as a Valve 220 .map."""

from __future__ import annotations
import argparse, json
from pathlib import Path
from generate_soe_g1_blockout import (
    box_brush, point_entity, brush_entity, stair_boxes, stair_boxes_y,
    FLOOR_TEX, WALL_TEX, CEILING_TEX, BLOCK_TEX, TRIGGER_TEX, NULL_TEX,
)

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "content" / "shadows_of_evil" / "g2_canal_blockout.json"
OUTPUT_PATH = ROOT / "overlay" / "assets" / "source" / "maps" / "soe_g2" / "soe_g2.map"
WORLD_WAD = "../../textures/wad/Example_02.wad"

def gen(spec):
    ents, wb = [], []

    # Sealed G2 test volume.
    wb += [
        box_brush((-320,384,-160),(896,1664,-128),FLOOR_TEX),
        box_brush((-320,384,-128),(-288,1664,512),WALL_TEX),
        box_brush((864,384,-128),(896,1664,512),WALL_TEX),
        box_brush((-320,384,-128),(896,416,512),WALL_TEX),
        box_brush((-320,1632,-128),(896,1664,512),WALL_TEX),
        box_brush((-320,384,512),(896,1664,544),CEILING_TEX),
    ]

    # Canal entry and banks.
    wb += [
        box_brush((96,448,-16),(672,704,0),FLOOR_TEX),
        box_brush((64,704,-112),(704,1136,-96),FLOOR_TEX),
        box_brush((64,704,-96),(152,1136,16),WALL_TEX),
        box_brush((616,704,-96),(704,1136,16),WALL_TEX),
        box_brush((152,704,-96),(616,736,-16),WALL_TEX),
        box_brush((152,1104,-96),(616,1136,-16),WALL_TEX),
    ]

    # Stairs down to the water and back up to high street.
    for a,b in stair_boxes_y(176,672,-96,8,20,12,112,1):
        wb.append(box_brush(a,b,BLOCK_TEX))
    for a,b in stair_boxes_y(520,1040,-96,10,18,22,112,1):
        wb.append(box_brush(a,b,BLOCK_TEX))

    # High street / bridges, deliberately narrow like the original.
    wb += [
        box_brush((152,784,112),(616,816,128),BLOCK_TEX),
        box_brush((152,976,112),(616,1008,128),BLOCK_TEX),
        box_brush((152,1136,112),(616,1216,128),BLOCK_TEX),
        box_brush((64,736,112),(152,1216,128),BLOCK_TEX),
        box_brush((616,736,112),(704,1216,128),BLOCK_TEX),
    ]

    # Ruby Rabbit shell, 3 floors with a front-door gap and stairwell.
    wb += [
        box_brush((-224,816,-16),(80,832,416),WALL_TEX),
        box_brush((-224,1216,-16),(80,1232,416),WALL_TEX),
        box_brush((-224,832,-16),(-208,1216,416),WALL_TEX),
        box_brush((64,832,-16),(80,1216,416),WALL_TEX),
        box_brush((-208,832,-16),(-144,1216,0),FLOOR_TEX),
        box_brush((-48,832,-16),(64,1216,0),FLOOR_TEX),
        box_brush((-208,832,112),(-64,1216,128),BLOCK_TEX),
        box_brush((16,832,112),(64,1216,128),BLOCK_TEX),
        box_brush((-208,832,240),(-64,1216,256),BLOCK_TEX),
        box_brush((16,832,240),(64,1216,256),BLOCK_TEX),
    ]
    for a,b in stair_boxes_y(-56,856,0,8,28,16,64,1):
        wb.append(box_brush(a,b,BLOCK_TEX))
    for a,b in stair_boxes_y(-56,984,128,8,28,16,64,1):
        wb.append(box_brush(a,b,BLOCK_TEX))

    # Station/platform and tram sightline shell.
    wb += [
        box_brush((208,1216,-16),(720,1248,0),FLOOR_TEX),
        box_brush((208,1248,-16),(720,1536,0),FLOOR_TEX),
        box_brush((208,1536,-16),(720,1568,0),FLOOR_TEX),
        box_brush((208,1248,0),(240,1536,224),WALL_TEX),
        box_brush((688,1248,0),(720,1536,224),WALL_TEX),
        box_brush((208,1248,224),(720,1536,240),CEILING_TEX),
        box_brush((320,1320,0),(600,1360,8),BLOCK_TEX),
        box_brush((320,1448,0),(600,1488,8),BLOCK_TEX),
    ]

    # Rift pocket with a Beast-opened entrance; no teleport entity yet.
    wb += [
        box_brush((32,752,-80),(240,768,128),WALL_TEX),
        box_brush((32,928,-80),(240,944,128),WALL_TEX),
        box_brush((32,768,-80),(48,928,128),WALL_TEX),
        box_brush((224,768,-80),(240,928,128),WALL_TEX),
        box_brush((32,768,-80),(240,928,-64),FLOOR_TEX),
    ]

    world=[
        "// Game: Nazi Zombies Portable","// Format: Valve",
        "// AUTO-GENERATED by scripts/generate_soe_g2_canal.py",
        "{",'"mapversion" "220"',f'"wad" "{WORLD_WAD}"','"classname" "worldspawn"',
        '"chaptertitle" "Shadows of Evil - G2 Canal Blockout"',
        '"location" "Morg City - Canal District"','"person" "NZ:P Android clean-room reconstruction"',
        '"light" "72"'
    ]
    for i,b in enumerate(wb): world += [f"// brush {i}",b]
    world.append("}")
    ents.append("\n".join(world))

    # Four test spawns at the Junction-facing entrance.
    for i,(x,y) in enumerate([(256,544),(304,544),(352,544),(400,544)],1):
        ents.append(point_entity(f"info_player_{i}_spawn",(x,y,40),weapon=0,currentmag=0,currentammo=0,angle=90))

    # Zones + stock zombie spawn groups.
    zones=[
        ("canal_entry",(96,448,0),(672,704,192),"soe_g2_entry","canal_lower"),
        ("canal_lower",(64,704,-96),(704,1136,112),"soe_g2_lower","canal_entry, canal_high, canal_rift"),
        ("canal_high",(64,720,128),(704,1232,336),"soe_g2_high","canal_lower, ruby_rabbit, canal_station"),
        ("ruby_rabbit",(-208,832,0),(64,1216,416),"soe_g2_ruby","canal_high"),
        ("canal_station",(224,1216,0),(704,1568,320),"soe_g2_station","canal_high"),
        ("canal_rift",(48,768,-64),(224,928,128),"soe_g2_rift","canal_lower"),
    ]
    for name,mi,ma,target,adj in zones:
        ents.append(brush_entity("spawn_zone",mi,ma,TRIGGER_TEX,zone_name=name,zone_target=target,adjacent_zones=adj))
    spawn_defs=[
        ((112,608,40),"soe_g2_entry",90),((656,608,40),"soe_g2_entry",90),
        ((112,896,-56),"soe_g2_lower",0),((656,1008,-56),"soe_g2_lower",180),
        ((112,1184,160),"soe_g2_high",0),((656,1184,160),"soe_g2_high",180),
        ((-176,1000,32),"soe_g2_ruby",0),((-176,1144,288),"soe_g2_ruby",0),
        ((272,1496,40),"soe_g2_station",270),((656,1496,40),"soe_g2_station",270)
    ]
    for org,target,ang in spawn_defs:
        ents.append(point_entity("spawn_zombie",org,spawnflags=7,angle=ang,targetname=target))

    # G2 gameplay anchors from the spec.
    for a in spec["gameplayAnchors"]:
        keys={k:v for k,v in a.items() if k not in {"classname","origin"}}
        ents.append(point_entity(a["classname"],a["origin"],**keys))

    # Visual/physical counterparts for powered interactions.
    ents.append(brush_entity("soe_powered_door",(-144,824,0),(-64,848,112),NULL_TEX,
                             targetname="soe_g2_ruby_access_blocker"))
    ents.append(brush_entity("soe_powered_door",(136,844,-64),(168,916,16),NULL_TEX,
                             targetname="soe_g2_badge_grate"))
    ents.append(point_entity("soe_beast_smash",(80,848,-16),
                             targetname="soe_g2_rift_smash",target="soe_g2_rift_door"))
    ents.append(brush_entity("soe_powered_door",(208,816,-64),(232,880,64),NULL_TEX,
                             targetname="soe_g2_rift_door"))

    # Sword/Ovum statue behind Ruby Rabbit stairs, hidden until later quest reveal.
    ents.append(point_entity("soe_sword_statue",(-184,880,32),style=2,targetname="soe_g2_canal_ovum_statue"))

    # Build tables at the Canal workbench.
    ents.append(point_entity("soe_shield_build_table",(16,1112,40),targetname="soe_g2_shield_table"))
    ents.append(point_entity("soe_servant_build_table",(72,1112,40),targetname="soe_g2_servant_table"))

    # Chain trap + Margwa bypass marker.
    ents.append(point_entity("info_notnull",(608,1104,48),targetname="soe_g2_chain_margwa_exit"))
    ents.append(point_entity("soe_chain_trap_volume",(544,1088,48),
                             targetname="soe_g2_chain_volume",target="soe_g2_chain_margwa_exit"))
    ents.append(point_entity("soe_chain_trap_switch",(504,1088,48),
                             target="soe_g2_chain_volume",cost=1000,wait=30))

    # Randomized Fumigator / shield / fuse candidates.
    for group in spec["randomized"]:
        for n,org in enumerate(group["candidates"],1):
            keys={"soe_random_group":group["group"],"targetname":f"soe_g2_random_{group['group']}_{n}"}
            if "style" in group: keys["style"]=group["style"]
            ents.append(point_entity(group["entity"],org,**keys))

    # Rift placeholder only: present for collision/sightline, intentionally inert.
    ents.append(point_entity("info_notnull",(128,848,-24),targetname="soe_g2_rift_visual_anchor"))

    # Lights.
    for org,b in [((320,608,176),300),((384,920,128),220),((384,1184,256),260),
                  ((-96,1016,352),280),((448,1376,176),300),((128,848,64),180)]:
        ents.append(point_entity("light",org,_light=b,wait=1,style=0))

    return "\n".join(ents)+"\n"

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--check",action="store_true")
    args=ap.parse_args()
    spec=json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    out=gen(spec)
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != out:
            raise SystemExit("G2 map is stale; regenerate and commit overlay/assets/source/maps/soe_g2/soe_g2.map")
        print("SOE G2 generated map is deterministic and up to date")
        return
    OUTPUT_PATH.parent.mkdir(parents=True,exist_ok=True)
    OUTPUT_PATH.write_text(out,encoding="utf-8",newline="\n")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
