#!/usr/bin/env python3
"""Generate the provisional Tram/Junction G7 blockout as a Valve 220 .map."""

from __future__ import annotations
import argparse, json
from pathlib import Path
from generate_soe_g1_blockout import (
    box_brush, point_entity, brush_entity,
    FLOOR_TEX, WALL_TEX, CEILING_TEX, BLOCK_TEX, TRIGGER_TEX,
)

ROOT=Path(__file__).resolve().parents[1]
SPEC_PATH=ROOT/"content"/"shadows_of_evil"/"g7_tram_blockout.json"
OUTPUT_PATH=ROOT/"overlay"/"assets"/"source"/"maps"/"soe_g7"/"soe_g7.map"
WORLD_WAD="../../textures/wad/Example_02.wad"

def gen(spec):
    ents,wb=[],[]

    # Sealed network test volume.
    wb += [
        box_brush((-1024,-1024,-96),(1024,1024,-64),FLOOR_TEX),
        box_brush((-1024,-1024,-64),(-992,1024,352),WALL_TEX),
        box_brush((992,-1024,-64),(1024,1024,352),WALL_TEX),
        box_brush((-1024,-1024,-64),(1024,-992,352),WALL_TEX),
        box_brush((-1024,992,-64),(1024,1024,352),WALL_TEX),
        box_brush((-1024,-1024,352),(1024,1024,384),CEILING_TEX),
    ]

    # Three station platforms + simple shelter masses.
    for station in spec["stations"]:
        x1,y1,z1,x2,y2,z2=station["platform"]
        wb.append(box_brush((x1,y1,z1),(x2,y2,z2),FLOOR_TEX))
        if station["id"]=="canal":
            wb += [
                box_brush((-896,160,0),(-448,192,224),WALL_TEX),
                box_brush((-896,-192,0),(-864,192,224),WALL_TEX),
                box_brush((-896,-192,208),(-448,192,224),CEILING_TEX),
            ]
        elif station["id"]=="footlight":
            wb += [
                box_brush((-288,864,0),(288,896,224),WALL_TEX),
                box_brush((-288,448,0),(-256,896,224),WALL_TEX),
                box_brush((-288,448,208),(288,896,224),CEILING_TEX),
            ]
        else:
            wb += [
                box_brush((448,160,0),(896,192,224),WALL_TEX),
                box_brush((864,-192,0),(896,192,224),WALL_TEX),
                box_brush((448,-192,208),(896,192,224),CEILING_TEX),
            ]

    # Junction central crossing / finale arena floor.
    wb += [
        box_brush((-256,-256,-16),(256,256,0),FLOOR_TEX),
    ]

    # Rail pairs. All three spokes physically converge through Junction.
    # Canal <-> Junction.
    wb += [
        box_brush((-896,-48,0),(256,-36,8),BLOCK_TEX),
        box_brush((-896,36,0),(256,48,8),BLOCK_TEX),
    ]
    # Waterfront <-> Junction.
    wb += [
        box_brush((-256,-48,0),(896,-36,8),BLOCK_TEX),
        box_brush((-256,36,0),(896,48,8),BLOCK_TEX),
    ]
    # Footlight <-> Junction.
    wb += [
        box_brush((-48,-256,0),(-36,896,8),BLOCK_TEX),
        box_brush((36,-256,0),(48,896,8),BLOCK_TEX),
    ]

    # Junction curb/keeper pads leave a wide center for the Gateworm + train.
    wb += [
        box_brush((-240,176,0),(-144,240,16),BLOCK_TEX),
        box_brush((144,176,0),(240,240,16),BLOCK_TEX),
        box_brush((-48,-240,0),(48,-144,16),BLOCK_TEX),
    ]

    world=[
        "// Game: Nazi Zombies Portable","// Format: Valve",
        "// AUTO-GENERATED by scripts/generate_soe_g7_tram.py",
        "{",
        '"mapversion" "220"',
        f'"wad" "{WORLD_WAD}"',
        '"classname" "worldspawn"',
        '"chaptertitle" "Shadows of Evil - G7 Tram / Finale Blockout"',
        '"location" "Morg City Tram Network / Junction"',
        '"person" "NZ:P Android clean-room reconstruction"',
        '"light" "72"',
    ]
    for i,b in enumerate(wb):
        world += [f"// brush {i}",b]
    world.append("}")
    ents.append("\n".join(world))

    # Test spawns at Junction.
    for i,(x,y) in enumerate([(-96,-96),(-32,-96),(32,-96),(96,-96)],1):
        ents.append(point_entity(
            f"info_player_{i}_spawn",(x,y,40),
            weapon=0,currentmag=0,currentammo=0,angle=90
        ))

    # Zones.
    zones=[
        ("junction_hub",(-256,-256,0),(256,256,224),"soe_g7_hub","canal_station, footlight_station, waterfront_station"),
        ("canal_station",(-896,-192,0),(-448,192,224),"soe_g7_canal","junction_hub"),
        ("footlight_station",(-288,448,0),(288,896,224),"soe_g7_footlight","junction_hub"),
        ("waterfront_station",(448,-192,0),(896,192,224),"soe_g7_waterfront","junction_hub"),
    ]
    for name,mi,ma,target,adj in zones:
        ents.append(brush_entity(
            "spawn_zone",mi,ma,TRIGGER_TEX,
            zone_name=name,zone_target=target,adjacent_zones=adj
        ))

    # Ambient AI pressure for navigation/finale testing.
    spawn_defs=[
        ((-224,208,40),"soe_g7_hub",270),((224,208,40),"soe_g7_hub",270),
        ((-224,-208,40),"soe_g7_hub",90),((224,-208,40),"soe_g7_hub",90),
        ((-840,144,40),"soe_g7_canal",270),((-504,-144,40),"soe_g7_canal",90),
        ((-224,840,40),"soe_g7_footlight",0),((224,504,40),"soe_g7_footlight",180),
        ((504,-144,40),"soe_g7_waterfront",90),((840,144,40),"soe_g7_waterfront",270),
    ]
    for org,target,ang in spawn_defs:
        ents.append(point_entity("spawn_zombie",org,spawnflags=7,angle=ang,targetname=target))

    # Physical tram brush starts at Canal and is relocated/aligned by its runtime.
    t=spec["tram"]
    ents.append(brush_entity(
        t["classname"],t["mins"],t["maxs"],BLOCK_TEX,
        targetname=t["targetname"],style=t["initialStation"],speed=t["speed"]
    ))

    # Station markers: marker origin represents desired tram mins.
    for station in spec["stations"]:
        ents.append(point_entity(
            "soe_tram_station_marker",station["marker"],
            style=station["style"],targetname=f"soe_g7_station_{station['id']}"
        ))

    # Every ride passes the Junction hub; the hub fires the finale train-hit hook.
    ents.append(point_entity(
        "soe_tram_hub_marker",spec["hub"]["marker"],
        target="soe_g7_train_hit",targetname="soe_g7_junction_hub_marker"
    ))

    # Two paid destination controls at every station.
    for i,b in enumerate(spec["buttons"],1):
        ents.append(point_entity(
            "soe_tram_button",b["origin"],
            style=b["station"],soe_tram_to_station=b["destination"],
            cost=b["cost"],target=t["targetname"],
            targetname=f"soe_g7_tram_button_{i}"
        ))

    # Randomized symbol presentation windows.
    for s in spec["symbolWindows"]:
        ents.append(point_entity(
            "soe_tram_symbol_window",s["origin"],
            style=s["style"],targetname=f"soe_g7_symbol_{s['district']}"
        ))

    # Finale station rail boxes.
    for box in spec["finale"]["stationBoxes"]:
        ents.append(point_entity(
            "soe_finale_station_box",box["origin"],
            style=box["style"],targetname=f"soe_g7_finale_box_{box['district']}"
        ))

    # Junction Gateworm collision hook + self-restoring visual.
    hit=spec["finale"]["trainHit"]
    ents.append(point_entity(
        hit["classname"],hit["origin"],
        targetname=hit["targetname"],target=hit["target"]
    ))
    worm=spec["finale"]["giantGateworm"]
    ents.append(point_entity(
        worm["classname"],worm["origin"],targetname=worm["targetname"]
    ))

    # Three central finale Keepers.
    for k in spec["finale"]["keepers"]:
        ents.append(point_entity(
            "soe_finale_keeper",k["origin"],style=k["style"],
            targetname=f"soe_g7_finale_keeper_{k['style']}"
        ))

    # Relightable Beast torches.
    for i,tch in enumerate(spec["finale"]["beastTorches"],1):
        ents.append(point_entity(
            "soe_finale_beast_torch",tch["origin"],
            targetname=f"soe_g7_finale_torch_{i}"
        ))

    # Corruption cleanse wisps.
    for i,org in enumerate(spec["finale"]["cleanseWisps"],1):
        ents.append(point_entity(
            "soe_finale_cleanse_wisp",org,
            targetname=f"soe_g7_cleanse_{i}"
        ))

    for d in spec["detailAnchors"]:
        keys={k:v for k,v in d.items() if k not in {"classname","origin","status"}}
        ents.append(point_entity(d["classname"],d["origin"],**keys))

    # Readability lighting.
    for org,b in [
        ((0,0,208),340),((-672,0,160),260),((672,0,160),260),((0,672,160),260),
        ((-320,0,128),180),((320,0,128),180),((0,320,128),180)
    ]:
        ents.append(point_entity("light",org,_light=b,wait=1,style=0))

    return "\n".join(ents)+"\n"

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--check",action="store_true")
    args=ap.parse_args()

    spec=json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    out=gen(spec)

    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != out:
            raise SystemExit("G7 map is stale; regenerate it")
        print("SOE G7 generated map is deterministic and up to date")
        return

    OUTPUT_PATH.parent.mkdir(parents=True,exist_ok=True)
    OUTPUT_PATH.write_text(out,encoding="utf-8",newline="\n")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")

if __name__=="__main__":
    main()
