#!/usr/bin/env python3
"""Generate the provisional Sacred Place G6 blockout as a Valve 220 .map."""

from __future__ import annotations
import argparse, json
from pathlib import Path
from generate_soe_g1_blockout import (
    box_brush, point_entity, brush_entity,
    FLOOR_TEX, WALL_TEX, CEILING_TEX, BLOCK_TEX, TRIGGER_TEX, NULL_TEX,
)

ROOT=Path(__file__).resolve().parents[1]
SPEC_PATH=ROOT/"content"/"shadows_of_evil"/"g6_sacred_place_blockout.json"
OUTPUT_PATH=ROOT/"overlay"/"assets"/"source"/"maps"/"soe_g6"/"soe_g6.map"
WORLD_WAD="../../textures/wad/Example_02.wad"

def gen(spec):
    ents, wb = [], []

    # Sealed Sacred Place test volume.
    wb += [
        box_brush((-896,-896,-256),(896,896,-224),FLOOR_TEX),
        box_brush((-896,-896,-224),(-864,896,512),WALL_TEX),
        box_brush((864,-896,-224),(896,896,512),WALL_TEX),
        box_brush((-896,-896,-224),(896,-864,512),WALL_TEX),
        box_brush((-896,864,-224),(896,896,512),WALL_TEX),
        box_brush((-896,-896,512),(896,896,544),CEILING_TEX),
    ]

    # Entry ledge: fifth ritual / capture table side.
    wb += [
        box_brush((-384,-768,-80),(384,-256,-64),FLOOR_TEX),
        box_brush((-384,-768,-64),(-352,-256,224),WALL_TEX),
        box_brush((352,-768,-64),(384,-256,224),WALL_TEX),
        box_brush((-384,-768,-64),(384,-736,224),WALL_TEX),
    ]

    # Far ledge: Gateworms + PaP approach.
    wb += [
        box_brush((-448,256,-80),(448,576,-64),FLOOR_TEX),
        box_brush((-448,256,-64),(-416,576,224),WALL_TEX),
        box_brush((416,256,-64),(448,576,224),WALL_TEX),
    ]

    # PaP recess, connected to far ledge only.
    wb += [
        box_brush((-224,576,-80),(224,800,-64),FLOOR_TEX),
        box_brush((-224,576,-64),(-192,800,256),WALL_TEX),
        box_brush((192,576,-64),(224,800,256),WALL_TEX),
        box_brush((-224,768,-64),(224,800,256),WALL_TEX),
        box_brush((-224,576,240),(224,800,256),CEILING_TEX),
    ]

    # Narrow safe landing lips at the ends of both wallrun routes.
    wb += [
        box_brush((-512,-256,-80),(-416,-160,-64),BLOCK_TEX),
        box_brush((-512,160,-80),(-416,256,-64),BLOCK_TEX),
        box_brush((416,-256,-80),(512,-160,-64),BLOCK_TEX),
        box_brush((416,160,-80),(512,256,-64),BLOCK_TEX),
    ]

    # Low arena detail / altar dais. No permanent floor crosses the abyss.
    wb += [
        box_brush((-96,-560,-64),(96,-432,-40),BLOCK_TEX),
        box_brush((-112,600,-64),(112,712,-40),BLOCK_TEX),
    ]

    world=[
        "// Game: Nazi Zombies Portable",
        "// Format: Valve",
        "// AUTO-GENERATED by scripts/generate_soe_g6_sacred_place.py",
        "// Sacred Place coordinates are clean-room provisional blockout dimensions.",
        "{",
        '"mapversion" "220"',
        f'"wad" "{WORLD_WAD}"',
        '"classname" "worldspawn"',
        '"chaptertitle" "Shadows of Evil - G6 Sacred Place Blockout"',
        '"location" "Sacred Place / Pack-a-Punch"',
        '"person" "NZ:P Android clean-room reconstruction"',
        '"light" "52"',
    ]
    for i,b in enumerate(wb):
        world += [f"// brush {i}", b]
    world.append("}")
    ents.append("\n".join(world))

    # Four standalone test spawns on entry ledge.
    for i,(x,y) in enumerate([(-72,-672),(-24,-672),(24,-672),(72,-672)],1):
        ents.append(point_entity(
            f"info_player_{i}_spawn",(x,y,-24),
            weapon=0,currentmag=0,currentammo=0,angle=90
        ))

    # Zones deliberately do not cover the abyss kill-space.
    zones=[
        ("sacred_entry",(-352,-736,-64),(352,-256,224),"soe_g6_entry","sacred_far"),
        ("sacred_far",(-416,256,-64),(416,576,224),"soe_g6_far","sacred_entry, sacred_pap"),
        ("sacred_pap",(-192,576,-64),(192,768,240),"soe_g6_pap_zone","sacred_far"),
    ]
    for name,mi,ma,target,adj in zones:
        ents.append(brush_entity(
            "spawn_zone",mi,ma,TRIGGER_TEX,
            zone_name=name,zone_target=target,adjacent_zones=adj
        ))

    spawn_defs=[
        ((-320,-688,-24),"soe_g6_entry",0),((320,-688,-24),"soe_g6_entry",180),
        ((-320,-320,-24),"soe_g6_entry",0),((320,-320,-24),"soe_g6_entry",180),
        ((-360,320,-24),"soe_g6_far",0),((360,320,-24),"soe_g6_far",180),
        ((-360,520,-24),"soe_g6_far",0),((360,520,-24),"soe_g6_far",180),
        ((-160,720,-24),"soe_g6_pap_zone",0),((160,720,-24),"soe_g6_pap_zone",180),
    ]
    for org,target,ang in spawn_defs:
        ents.append(point_entity(
            "spawn_zombie",org,spawnflags=7,angle=ang,targetname=target
        ))

    # Mapper-facing gameplay entities from the spec.
    for a in spec["gameplayAnchors"]:
        keys={k:v for k,v in a.items() if k not in {"classname","origin"}}
        ents.append(point_entity(a["classname"],a["origin"],**keys))

    # Gateworm-created run surfaces and attached wallrun trigger volumes.
    for g in spec["gatewormGeometry"]:
        ents.append(brush_entity(
            g["classname"],g["mins"],g["maxs"],BLOCK_TEX,
            targetname=g["targetname"]
        ))
        v=g["wallrunVolume"]
        ents.append(brush_entity(
            "soe_wallrun_volume",v["mins"],v["maxs"],TRIGGER_TEX,
            angles=" ".join(str(x) for x in v["angles"]),
            speed=v["speed"],wait=v["wait"],
            targetname=g["targetname"]+"_volume"
        ))

    # Final-ritual PaP portal cover.
    for d in spec["poweredGeometry"]:
        ents.append(brush_entity(
            d["classname"],d["mins"],d["maxs"],NULL_TEX,
            targetname=d["targetname"]
        ))

    # Abyss is explicitly lethal; there is no hidden traversal bridge.
    for h in spec["hazards"]:
        ents.append(brush_entity(
            h["classname"],h["mins"],h["maxs"],TRIGGER_TEX,
            dmg=h["dmg"],wait=h["wait"],targetname=h["targetname"]
        ))

    # Readable blockout lighting.
    for org,b in [
        ((0,-592,176),280),((-280,-352,144),210),((280,-352,144),210),
        ((-280,352,144),230),((280,352,144),230),((0,640,160),340),
        ((0,32,224),170),
    ]:
        ents.append(point_entity("light",org,_light=b,wait=1,style=0))

    return "\n".join(ents)+"\n"

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--check",action="store_true")
    args=ap.parse_args()

    spec=json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    out=gen(spec)

    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != out:
            raise SystemExit("G6 map is stale; regenerate it")
        print("SOE G6 generated map is deterministic and up to date")
        return

    OUTPUT_PATH.parent.mkdir(parents=True,exist_ok=True)
    OUTPUT_PATH.write_text(out,encoding="utf-8",newline="\n")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")

if __name__=="__main__":
    main()
