#!/usr/bin/env python3
"""Generate the provisional Waterfront District G4 blockout as Valve 220 .map."""

from __future__ import annotations
import argparse, json
from pathlib import Path
from generate_soe_g1_blockout import (
    box_brush, point_entity, brush_entity, stair_boxes, stair_boxes_y,
    FLOOR_TEX, WALL_TEX, CEILING_TEX, BLOCK_TEX, TRIGGER_TEX, NULL_TEX,
)

ROOT=Path(__file__).resolve().parents[1]
SPEC_PATH=ROOT/"content"/"shadows_of_evil"/"g4_waterfront_blockout.json"
OUTPUT_PATH=ROOT/"overlay"/"assets"/"source"/"maps"/"soe_g4"/"soe_g4.map"
WORLD_WAD="../../textures/wad/Example_02.wad"

def gen(spec):
    ents,wb=[],[]
    wb += [
        box_brush((-320,-1760,-128),(896,-384,-96),FLOOR_TEX),
        box_brush((-320,-1760,-96),(-288,-384,512),WALL_TEX),
        box_brush((864,-1760,-96),(896,-384,512),WALL_TEX),
        box_brush((-320,-1760,-96),(896,-1728,512),WALL_TEX),
        box_brush((-320,-416,-96),(896,-384,512),WALL_TEX),
        box_brush((-320,-1760,512),(896,-384,544),CEILING_TEX),
    ]

    # Junction-facing entry and narrow lower Waterfront.
    wb += [
        box_brush((96,-704,-16),(672,-448,0),FLOOR_TEX),
        box_brush((64,-1216,-80),(704,-704,-64),FLOOR_TEX),
        box_brush((64,-1216,-64),(144,-704,48),WALL_TEX),
        box_brush((624,-1216,-64),(704,-704,48),WALL_TEX),
        box_brush((144,-736,-64),(624,-704,32),WALL_TEX),
    ]

    # Docks / lower combat islands.
    wb += [
        box_brush((160,-1184,-64),(352,-1040,-48),BLOCK_TEX),
        box_brush((416,-1056,-64),(608,-896,-48),BLOCK_TEX),
        box_brush((192,-880,-64),(384,-768,-48),BLOCK_TEX),
    ]

    # High Street narrow walkways with two drop envelopes.
    wb += [
        box_brush((144,-1280,112),(624,-1216,128),BLOCK_TEX),
        box_brush((144,-1088,112),(624,-1024,128),BLOCK_TEX),
        box_brush((144,-1280,112),(208,-1088,128),BLOCK_TEX),
        box_brush((560,-1280,112),(624,-1088,128),BLOCK_TEX),
    ]
    for a,b in stair_boxes_y(560,-1184,-64,10,18,20,96,1):
        wb.append(box_brush(a,b,BLOCK_TEX))

    # The Anvil: compact gym with ring at center.
    wb += [
        box_brush((-240,-1232,-16),(80,-1216,320),WALL_TEX),
        box_brush((-240,-832,-16),(80,-816,320),WALL_TEX),
        box_brush((-240,-1216,-16),(-224,-832,320),WALL_TEX),
        box_brush((64,-1216,-16),(80,-832,320),WALL_TEX),
        box_brush((-224,-1216,-16),(64,-832,0),FLOOR_TEX),
        # Ring platform and corner posts.
        box_brush((-176,-1144,0),(-16,-984,20),BLOCK_TEX),
        box_brush((-184,-1152,0),(-168,-1136,80),BLOCK_TEX),
        box_brush((-24,-1152,0),(-8,-1136,80),BLOCK_TEX),
        box_brush((-184,-992,0),(-168,-976,80),BLOCK_TEX),
        box_brush((-24,-992,0),(-8,-976,80),BLOCK_TEX),
    ]

    # Waterfront station.
    wb += [
        box_brush((208,-1616,-16),(720,-1584,0),FLOOR_TEX),
        box_brush((208,-1584,-16),(720,-1232,0),FLOOR_TEX),
        box_brush((208,-1232,-16),(720,-1216,0),FLOOR_TEX),
        box_brush((208,-1584,0),(240,-1232,224),WALL_TEX),
        box_brush((688,-1584,0),(720,-1232,224),WALL_TEX),
        box_brush((208,-1584,224),(720,-1232,240),CEILING_TEX),
        box_brush((320,-1488,0),(600,-1448,8),BLOCK_TEX),
        box_brush((320,-1360,0),(600,-1320,8),BLOCK_TEX),
    ]

    # Rift pocket.
    wb += [
        box_brush((48,-960,-80),(240,-944,128),WALL_TEX),
        box_brush((48,-768,-80),(240,-752,128),WALL_TEX),
        box_brush((48,-944,-80),(64,-768,128),WALL_TEX),
        box_brush((224,-944,-80),(240,-768,128),WALL_TEX),
        box_brush((48,-944,-80),(240,-768,-64),FLOOR_TEX),
    ]

    world=[
        "// Game: Nazi Zombies Portable","// Format: Valve",
        "// AUTO-GENERATED by scripts/generate_soe_g4_waterfront.py",
        "{",'"mapversion" "220"',f'"wad" "{WORLD_WAD}"','"classname" "worldspawn"',
        '"chaptertitle" "Shadows of Evil - G4 Waterfront Blockout"',
        '"location" "Morg City - Waterfront District"',
        '"person" "NZ:P Android clean-room reconstruction"','"light" "72"'
    ]
    for i,b in enumerate(wb): world += [f"// brush {i}",b]
    world.append("}")
    ents.append("\n".join(world))

    for i,(x,y) in enumerate([(256,-544),(304,-544),(352,-544),(400,-544)],1):
        ents.append(point_entity(f"info_player_{i}_spawn",(x,y,40),weapon=0,currentmag=0,currentammo=0,angle=270))

    zones=[
        ("waterfront_entry",(96,-704,0),(672,-448,192),"soe_g4_entry","waterfront_lower"),
        ("waterfront_lower",(64,-1216,-64),(704,-704,224),"soe_g4_lower","waterfront_entry, waterfront_high, anvil_gym, waterfront_rift, waterfront_station"),
        ("waterfront_high",(64,-1280,128),(704,-736,352),"soe_g4_high","waterfront_lower, waterfront_station"),
        ("anvil_gym",(-224,-1216,0),(64,-832,320),"soe_g4_anvil","waterfront_lower"),
        ("waterfront_station",(224,-1600,0),(704,-1216,320),"soe_g4_station","waterfront_lower, waterfront_high"),
        ("waterfront_rift",(64,-944,-64),(224,-768,128),"soe_g4_rift","waterfront_lower"),
    ]
    for name,mi,ma,target,adj in zones:
        ents.append(brush_entity("spawn_zone",mi,ma,TRIGGER_TEX,zone_name=name,zone_target=target,adjacent_zones=adj))

    spawn_defs=[
        ((112,-608,40),"soe_g4_entry",0),((656,-608,40),"soe_g4_entry",180),
        ((112,-816,-24),"soe_g4_lower",0),((656,-1056,-24),"soe_g4_lower",180),
        ((112,-1200,160),"soe_g4_high",0),((656,-1200,160),"soe_g4_high",180),
        ((-192,-1184,40),"soe_g4_anvil",0),((32,-864,40),"soe_g4_anvil",180),
        ((272,-1544,40),"soe_g4_station",90),((656,-1544,40),"soe_g4_station",90),
    ]
    for org,target,ang in spawn_defs:
        ents.append(point_entity("spawn_zombie",org,spawnflags=7,angle=ang,targetname=target))

    for a in spec["gameplayAnchors"]:
        keys={k:v for k,v in a.items() if k not in {"classname","origin"}}
        ents.append(point_entity(a["classname"],a["origin"],**keys))

    for d in spec["poweredGeometry"]:
        ents.append(brush_entity(d["classname"],d["mins"],d["maxs"],NULL_TEX,targetname=d["targetname"]))

    for d in spec["buyableDoors"]:
        ents.append(brush_entity("func_door_nzp",d["mins"],d["maxs"],NULL_TEX,
                                 targetname=d["id"],cost=d["cost"],speed=100,sounds=1,
                                 wait=4,lip=8,distance=96,dmg=0,health=0,spawnflags=0))

    for group in spec["randomized"]:
        for n,org in enumerate(group["candidates"],1):
            ents.append(point_entity(group["entity"],org,
                                     soe_random_group=group["group"],
                                     targetname=f"soe_g4_random_{group['group']}_{n}",
                                     style=group["style"]))

    # Detail anchors with native runtime where available.
    for d in spec["detailAnchors"]:
        keys={k:v for k,v in d.items() if k not in {"classname","origin","status"}}
        if d["classname"]=="mystery_box_tp_spot":
            keys.setdefault("model","models/machines/mystery.mdl")
            keys.setdefault("angles","0 180 0")
        ents.append(point_entity(d["classname"],d["origin"],**keys))

    ents.append(point_entity("soe_shield_build_table",(16,-1112,40),targetname="soe_g4_shield_table"))
    ents.append(point_entity("soe_servant_build_table",(72,-1112,40),targetname="soe_g4_servant_table"))

    # Inert portal anchor until G5.
    ents.append(point_entity("info_notnull",(128,-848,-24),targetname="soe_g4_rift_portal_anchor"))

    for org,b in [((320,-608,176),300),((384,-920,144),220),((384,-1184,256),260),
                  ((-96,-1088,192),300),((448,-1376,176),300),((128,-848,64),180)]:
        ents.append(point_entity("light",org,_light=b,wait=1,style=0))

    return "\n".join(ents)+"\n"

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--check",action="store_true"); args=ap.parse_args()
    spec=json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    out=gen(spec)
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != out:
            raise SystemExit("G4 map is stale; regenerate it")
        print("SOE G4 generated map is deterministic and up to date"); return
    OUTPUT_PATH.parent.mkdir(parents=True,exist_ok=True)
    OUTPUT_PATH.write_text(out,encoding="utf-8",newline="\n")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")

if __name__=="__main__": main()
