#!/usr/bin/env python3
"""Generate the provisional Rift/Subway G5 blockout as a Valve 220 .map."""

from __future__ import annotations
import argparse, json
from pathlib import Path
from generate_soe_g1_blockout import (
    box_brush, point_entity, brush_entity, stair_boxes, stair_boxes_y,
    FLOOR_TEX, WALL_TEX, CEILING_TEX, BLOCK_TEX, TRIGGER_TEX, NULL_TEX,
)

from soe_mainquest_geometry import append_phase_mainquest_entities

ROOT=Path(__file__).resolve().parents[1]
SPEC_PATH=ROOT/"content"/"shadows_of_evil"/"g5_rift_blockout.json"
OUTPUT_PATH=ROOT/"overlay"/"assets"/"source"/"maps"/"soe_g5"/"soe_g5.map"
WORLD_WAD="../../textures/wad/Example_02.wad"

def gen(spec):
    ents,wb=[],[]

    # Sealed underground volume.
    wb += [
        box_brush((-768,-640,-192),(768,640,-160),FLOOR_TEX),
        box_brush((-768,-640,-160),(-736,640,480),WALL_TEX),
        box_brush((736,-640,-160),(768,640,480),WALL_TEX),
        box_brush((-768,-640,-160),(768,-608,480),WALL_TEX),
        box_brush((-768,608,-160),(768,640,480),WALL_TEX),
        box_brush((-768,-640,480),(768,640,512),CEILING_TEX),
    ]

    # Lower subway hall / loop.
    wb += [
        box_brush((-640,-384,-112),(640,320,-96),FLOOR_TEX),
        box_brush((-640,-384,-96),(-608,320,160),WALL_TEX),
        box_brush((608,-384,-96),(640,320,160),WALL_TEX),
        box_brush((-640,-384,-96),(640,-352,160),WALL_TEX),
        # Keep north open where stairs climb to upper concourse.
        box_brush((-640,288,-96),(-192,320,160),WALL_TEX),
        box_brush((192,288,-96),(640,320,160),WALL_TEX),
    ]

    # Three portal counterpart alcoves.
    wb += [
        # Canal west / beside Widow's Wine.
        box_brush((-640,-288,-96),(-400,-256,160),WALL_TEX),
        box_brush((-640,-64,-96),(-400,-32,160),WALL_TEX),
        # Footlight east / opposite side.
        box_brush((400,-288,-96),(640,-256,160),WALL_TEX),
        box_brush((400,-64,-96),(640,-32,160),WALL_TEX),
    ]

    # Upper concourse, two flights above lower floor.
    wb += [
        box_brush((-352,160,112),(352,560,128),BLOCK_TEX),
        box_brush((-352,160,128),(-320,560,352),WALL_TEX),
        box_brush((320,160,128),(352,560,352),WALL_TEX),
        box_brush((-352,528,128),(352,560,352),WALL_TEX),
    ]
    # Two stair runs from lower loop up to Mule/Junction landing.
    for a,b in stair_boxes_y(-176,240,-96,8,20,16,112,1):
        wb.append(box_brush(a,b,BLOCK_TEX))
    for a,b in stair_boxes_y(-176,400,32,8,16,12,112,1):
        wb.append(box_brush(a,b,BLOCK_TEX))

    # Derelict subway car + platform envelope; car is a hollow-ish obstacle.
    wb += [
        box_brush((192,-336,-80),(576,-304,112),WALL_TEX),
        box_brush((192,176,-80),(576,208,112),WALL_TEX),
        box_brush((192,-304,-80),(224,176,112),WALL_TEX),
        box_brush((544,-304,-80),(576,176,112),WALL_TEX),
        box_brush((192,-304,96),(576,176,112),CEILING_TEX),
        box_brush((232,-296,-96),(536,-280,-88),BLOCK_TEX),
        box_brush((232,152,-96),(536,168,-88),BLOCK_TEX),
    ]

    # Sword wall niche beneath the stairs. Physical wall is a powered entity.
    wb += [
        box_brush((-144,64,-96),(-96,224,160),WALL_TEX),
        box_brush((160,64,-96),(208,224,160),WALL_TEX),
        box_brush((-96,64,144),(160,224,160),CEILING_TEX),
    ]

    # Sacred Place approach is intentionally sealed at G5.
    wb += [
        box_brush((-224,-608,-96),(-192,-384,192),WALL_TEX),
        box_brush((192,-608,-96),(224,-384,192),WALL_TEX),
        box_brush((-192,-608,-96),(192,-576,192),WALL_TEX),
        box_brush((-192,-416,-96),(192,-384,192),WALL_TEX),
        box_brush((-192,-576,176),(192,-416,192),CEILING_TEX),
        box_brush((-192,-576,-112),(192,-416,-96),FLOOR_TEX),
    ]

    world=[
        "// Game: Nazi Zombies Portable","// Format: Valve",
        "// AUTO-GENERATED by scripts/generate_soe_g5_rift.py",
        "{",'"mapversion" "220"',f'"wad" "{WORLD_WAD}"','"classname" "worldspawn"',
        '"chaptertitle" "Shadows of Evil - G5 Rift/Subway Blockout"',
        '"location" "Morg City - The Rift"',
        '"person" "NZ:P Android clean-room reconstruction"','"light" "58"'
    ]
    for i,b in enumerate(wb): world += [f"// brush {i}",b]
    world.append("}")
    ents.append("\n".join(world))

    # Standalone spawn cluster near lower-center hub.
    for i,(x,y) in enumerate([(-72,-240),(-24,-240),(24,-240),(72,-240)],1):
        ents.append(point_entity(f"info_player_{i}_spawn",(x,y,-48),weapon=0,currentmag=0,currentammo=0,angle=90))

    zones=[
        ("rift_lower",(-608,-352,-96),(608,288,160),"soe_g5_lower","rift_upper, rift_portal_canal, rift_portal_footlight, rift_sword_wall, rift_train, rift_sacred_gate"),
        ("rift_upper",(-320,160,128),(320,528,352),"soe_g5_upper","rift_lower, rift_portal_waterfront, rift_junction_shortcut"),
        ("rift_portal_canal",(-608,-256,-32),(-400,-64,160),"soe_g5_canal_portal","rift_lower"),
        ("rift_portal_waterfront",(-320,256,128),(-96,480,320),"soe_g5_waterfront_portal","rift_upper"),
        ("rift_portal_footlight",(400,-256,-32),(608,-64,160),"soe_g5_footlight_portal","rift_lower"),
        ("rift_sword_wall",(-96,-32,-16),(160,192,160),"soe_g5_sword_room","rift_lower"),
        ("rift_train",(176,-352,-32),(608,224,192),"soe_g5_train","rift_lower"),
        ("rift_junction_shortcut",(-160,416,128),(160,576,320),"soe_g5_junction","rift_upper"),
        ("rift_sacred_gate",(-192,-576,-64),(192,-384,192),"soe_g5_sacred","rift_lower"),
    ]
    for name,mi,ma,target,adj in zones:
        ents.append(brush_entity("spawn_zone",mi,ma,TRIGGER_TEX,zone_name=name,zone_target=target,adjacent_zones=adj))

    # General lower/upper zombie pressure. First-entry Keepers are separate runtime.
    spawn_defs=[
        ((-560,-320,-48),"soe_g5_lower",0),((560,-320,-48),"soe_g5_lower",180),
        ((-560,224,-48),"soe_g5_lower",0),((560,224,-48),"soe_g5_lower",180),
        ((-288,496,176),"soe_g5_upper",0),((288,496,176),"soe_g5_upper",180),
        ((-560,-160,-16),"soe_g5_canal_portal",0),((560,-160,-16),"soe_g5_footlight_portal",180),
        ((256,160,-48),"soe_g5_train",270),((512,-256,-48),"soe_g5_train",90),
    ]
    for org,target,ang in spawn_defs:
        ents.append(point_entity("spawn_zombie",org,spawnflags=7,angle=ang,targetname=target))

    # Core gameplay anchors.
    for a in spec["gameplayAnchors"]:
        keys={k:v for k,v in a.items() if k not in {"classname","origin"}}
        ents.append(point_entity(a["classname"],a["origin"],**keys))

    # Nine-symbol wall. Every glyph targets the guarded wall gate; wrong inputs
    # invoke it too, but the gate refuses to open until global validation passed.
    for idx,g in enumerate(spec["glyphs"]):
        keys={k:v for k,v in g.items() if k not in {"classname","origin"}}
        keys["targetname"]=f"soe_g5_glyph_{idx}"
        ents.append(point_entity(g["classname"],g["origin"],**keys))

    # Physical doors controlled by Beast/glyph runtime.
    for d in spec["poweredGeometry"]:
        ents.append(brush_entity(d["classname"],d["mins"],d["maxs"],NULL_TEX,targetname=d["targetname"]))

    # Development portal harness: three visible Rift sources point back to each
    # corresponding underground destination so teleport code can be exercised.
    for name,org,target in [
        ("soe_g5_test_portal_canal",(-520,-112,-16),"soe_g5_arrival_canal"),
        ("soe_g5_test_portal_waterfront",(-240,304,176),"soe_g5_arrival_waterfront"),
        ("soe_g5_test_portal_footlight",(520,-112,-16),"soe_g5_arrival_footlight"),
    ]:
        ents.append(point_entity("soe_rift_portal",org,spawnflags=1,targetname=name,target2=target,
                                 useprint_string_1="Hold %b to Open Rift"))

    # Lower-floor Mule/Widow details + station debris anchors.
    ents.append(point_entity("info_notnull",(-448,-240,32),targetname="soe_g5_widows_box_spacing_anchor"))
    ents.append(point_entity("info_notnull",(384,-80,24),targetname="soe_g5_subway_car_anchor"))

    # Cross-phase Reborn Sword / Flag quest anchors from the shared source of truth.
    append_phase_mainquest_entities(ents, "g5", point_entity)

    for org,b in [
        ((-448,-160,112),260),((448,-160,112),240),((0,-64,128),220),
        ((-112,352,288),300),((112,480,288),240),((0,-496,112),150)
    ]:
        ents.append(point_entity("light",org,_light=b,wait=1,style=0))

    return "\n".join(ents)+"\n"

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--check",action="store_true"); args=ap.parse_args()
    spec=json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    out=gen(spec)
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != out:
            raise SystemExit("G5 map is stale; regenerate it")
        print("SOE G5 generated map is deterministic and up to date"); return
    OUTPUT_PATH.parent.mkdir(parents=True,exist_ok=True)
    OUTPUT_PATH.write_text(out,encoding="utf-8",newline="\n")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")

if __name__=="__main__": main()
